services:
  - type: web
    name: adminpanel-batlogger
    env: python
    plan: free
    region: frankfurt  # Eller nærmeste region for deg
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
